// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gdi_smart_proto.proto

package nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf;

public final class GdiSmartProto {
  private GdiSmartProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SmartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:garmin_vivomovehr.Smart)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    boolean hasDeviceStatusService();
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService getDeviceStatusService();

    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    boolean hasFindMyWatchService();
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService getFindMyWatchService();

    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    boolean hasCoreService();
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService getCoreService();

    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    boolean hasSmsNotificationService();
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService getSmsNotificationService();
  }
  /**
   * Protobuf type {@code garmin_vivomovehr.Smart}
   */
  public  static final class Smart extends
      com.google.protobuf.GeneratedMessageLite<
          Smart, Smart.Builder> implements
      // @@protoc_insertion_point(message_implements:garmin_vivomovehr.Smart)
      SmartOrBuilder {
    private Smart() {
    }
    private int bitField0_;
    public static final int DEVICE_STATUS_SERVICE_FIELD_NUMBER = 8;
    private nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService deviceStatusService_;
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    @java.lang.Override
    public boolean hasDeviceStatusService() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService getDeviceStatusService() {
      return deviceStatusService_ == null ? nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService.getDefaultInstance() : deviceStatusService_;
    }
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    private void setDeviceStatusService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      deviceStatusService_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    private void setDeviceStatusService(
        nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService.Builder builderForValue) {
      deviceStatusService_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeDeviceStatusService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (deviceStatusService_ != null &&
          deviceStatusService_ != nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService.getDefaultInstance()) {
        deviceStatusService_ =
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService.newBuilder(deviceStatusService_).mergeFrom(value).buildPartial();
      } else {
        deviceStatusService_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
     */
    private void clearDeviceStatusService() {  deviceStatusService_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int FIND_MY_WATCH_SERVICE_FIELD_NUMBER = 12;
    private nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService findMyWatchService_;
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    @java.lang.Override
    public boolean hasFindMyWatchService() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService getFindMyWatchService() {
      return findMyWatchService_ == null ? nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService.getDefaultInstance() : findMyWatchService_;
    }
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    private void setFindMyWatchService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      findMyWatchService_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    private void setFindMyWatchService(
        nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService.Builder builderForValue) {
      findMyWatchService_ = builderForValue.build();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeFindMyWatchService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (findMyWatchService_ != null &&
          findMyWatchService_ != nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService.getDefaultInstance()) {
        findMyWatchService_ =
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService.newBuilder(findMyWatchService_).mergeFrom(value).buildPartial();
      } else {
        findMyWatchService_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
     */
    private void clearFindMyWatchService() {  findMyWatchService_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int CORE_SERVICE_FIELD_NUMBER = 13;
    private nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService coreService_;
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    @java.lang.Override
    public boolean hasCoreService() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService getCoreService() {
      return coreService_ == null ? nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService.getDefaultInstance() : coreService_;
    }
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    private void setCoreService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      coreService_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    private void setCoreService(
        nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService.Builder builderForValue) {
      coreService_ = builderForValue.build();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCoreService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (coreService_ != null &&
          coreService_ != nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService.getDefaultInstance()) {
        coreService_ =
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService.newBuilder(coreService_).mergeFrom(value).buildPartial();
      } else {
        coreService_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
     */
    private void clearCoreService() {  coreService_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static final int SMS_NOTIFICATION_SERVICE_FIELD_NUMBER = 16;
    private nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService smsNotificationService_;
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    @java.lang.Override
    public boolean hasSmsNotificationService() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService getSmsNotificationService() {
      return smsNotificationService_ == null ? nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService.getDefaultInstance() : smsNotificationService_;
    }
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    private void setSmsNotificationService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      smsNotificationService_ = value;
      bitField0_ |= 0x00000008;
      }
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    private void setSmsNotificationService(
        nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService.Builder builderForValue) {
      smsNotificationService_ = builderForValue.build();
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeSmsNotificationService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (smsNotificationService_ != null &&
          smsNotificationService_ != nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService.getDefaultInstance()) {
        smsNotificationService_ =
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService.newBuilder(smsNotificationService_).mergeFrom(value).buildPartial();
      } else {
        smsNotificationService_ = value;
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
     */
    private void clearSmsNotificationService() {  smsNotificationService_ = null;
      bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code garmin_vivomovehr.Smart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart, Builder> implements
        // @@protoc_insertion_point(builder_implements:garmin_vivomovehr.Smart)
        nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.SmartOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      @java.lang.Override
      public boolean hasDeviceStatusService() {
        return instance.hasDeviceStatusService();
      }
      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService getDeviceStatusService() {
        return instance.getDeviceStatusService();
      }
      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      public Builder setDeviceStatusService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService value) {
        copyOnWrite();
        instance.setDeviceStatusService(value);
        return this;
        }
      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      public Builder setDeviceStatusService(
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService.Builder builderForValue) {
        copyOnWrite();
        instance.setDeviceStatusService(builderForValue);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      public Builder mergeDeviceStatusService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiDeviceStatus.DeviceStatusService value) {
        copyOnWrite();
        instance.mergeDeviceStatusService(value);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.DeviceStatusService device_status_service = 8;</code>
       */
      public Builder clearDeviceStatusService() {  copyOnWrite();
        instance.clearDeviceStatusService();
        return this;
      }

      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      @java.lang.Override
      public boolean hasFindMyWatchService() {
        return instance.hasFindMyWatchService();
      }
      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService getFindMyWatchService() {
        return instance.getFindMyWatchService();
      }
      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      public Builder setFindMyWatchService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService value) {
        copyOnWrite();
        instance.setFindMyWatchService(value);
        return this;
        }
      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      public Builder setFindMyWatchService(
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService.Builder builderForValue) {
        copyOnWrite();
        instance.setFindMyWatchService(builderForValue);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      public Builder mergeFindMyWatchService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiFindMyWatch.FindMyWatchService value) {
        copyOnWrite();
        instance.mergeFindMyWatchService(value);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.FindMyWatchService find_my_watch_service = 12;</code>
       */
      public Builder clearFindMyWatchService() {  copyOnWrite();
        instance.clearFindMyWatchService();
        return this;
      }

      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      @java.lang.Override
      public boolean hasCoreService() {
        return instance.hasCoreService();
      }
      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService getCoreService() {
        return instance.getCoreService();
      }
      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      public Builder setCoreService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService value) {
        copyOnWrite();
        instance.setCoreService(value);
        return this;
        }
      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      public Builder setCoreService(
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService.Builder builderForValue) {
        copyOnWrite();
        instance.setCoreService(builderForValue);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      public Builder mergeCoreService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiCore.CoreService value) {
        copyOnWrite();
        instance.mergeCoreService(value);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.CoreService core_service = 13;</code>
       */
      public Builder clearCoreService() {  copyOnWrite();
        instance.clearCoreService();
        return this;
      }

      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      @java.lang.Override
      public boolean hasSmsNotificationService() {
        return instance.hasSmsNotificationService();
      }
      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService getSmsNotificationService() {
        return instance.getSmsNotificationService();
      }
      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      public Builder setSmsNotificationService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService value) {
        copyOnWrite();
        instance.setSmsNotificationService(value);
        return this;
        }
      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      public Builder setSmsNotificationService(
          nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService.Builder builderForValue) {
        copyOnWrite();
        instance.setSmsNotificationService(builderForValue);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      public Builder mergeSmsNotificationService(nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmsNotification.SmsNotificationService value) {
        copyOnWrite();
        instance.mergeSmsNotificationService(value);
        return this;
      }
      /**
       * <code>optional .garmin_vivomovehr.SmsNotificationService sms_notification_service = 16;</code>
       */
      public Builder clearSmsNotificationService() {  copyOnWrite();
        instance.clearSmsNotificationService();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:garmin_vivomovehr.Smart)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "deviceStatusService_",
              "findMyWatchService_",
              "coreService_",
              "smsNotificationService_",
            };
            java.lang.String info =
                "\u0001\u0004\u0000\u0001\b\u0010\u0004\u0000\u0000\u0001\b\t\u0000\f\u0409\u0001" +
                "\r\t\u0002\u0010\t\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:garmin_vivomovehr.Smart)
    private static final nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart DEFAULT_INSTANCE;
    static {
      Smart defaultInstance = new Smart();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Smart.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.service.devices.vivomovehr.protobuf.GdiSmartProto.Smart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Smart> PARSER;

    public static com.google.protobuf.Parser<Smart> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
